/*
The fun and easy project "Guess the Number" is a short Java project that allows the user to guess the number generated by the computer a involves the following steps: 

1.The system generates a random number from a given range, say 1 to 100. 
2.The user is prompted to enter their given number in a displayed dialogue box. 
3.The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number. 
4.The game continues under the user guessing the number. 

You can also incorporate further details as: • Limiting the number of attempts. • Adding more rounds.  • Giving points based on the number of attempts. 
*/
import java.util.*;
class Guess_The_Number
{
    public static void main(String args[])
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter limit of guessing : ");
        int w=sc.nextInt();
        System.out.println("Hello\nWelcome to the number guessing game\nYou have to guess a number between 1 to "+w);
        System.out.print("Enter \nstart : start the game \nend : end the game\nhere : ");
        String t = sc.next();
        while (t.equals("start") || t.equals("again")) {
            System.out.print("Enter the number of attempts you want to try : ");
            int h = sc.nextInt();
            int e = h;
            double n = 100.0 / e;
            System.out.print("\nEnter 1 to start guessing : ");
            int u = sc.nextInt();
            if (u == 1) {
                int x = (int) (Math.random() * w) + 1;
                int y = 0;
                int j = 1;
                int p;
                while (y == 0 && h != 0) {
                    System.out.print("\nGuess the number : ");
                    p = sc.nextInt();
                    if (p == x) {
                        System.out.println("You guessed the number : " + x + "\nin attempt number : " + j);
                        if(j==1)
                        System.out.println("Your score is : "+(float)(100)+" percent");
                        else if(j==(e-1))
                        System.out.println("Your somehow guessed it in the last attempt");
                        else
                        System.out.println("Your score is : "+(float)(100-(n*j))+" percent");
                        y = 1;
                        h--;
                    } else {
                        j++;
                        if (h == 1) {
                            System.out.println("\nYou couldn't guess the number\nin " + e + " attempts.\nIt was : " + x);
                            t = "end";
                            y=1;
                        } else {
                            if (p > x)
                                System.out.println("Guess Lower");
                            else
                                System.out.println("Guess Higher");
                            System.out.println("Number of attempts left are : " + (--h));
                        }
                    }
                }
                System.out.print("\nEnter \nagain : to play again\nend : to end game\nhere : ");
                t = sc.next();
            } else{
                t = "end";}
            }
            System.out.println("Thank You!");
            sc.close();
    }
}
